# 表示使用的 Kubernetes API 版本
apiVersion: apps/v1
# 表示这是一个部署对象
kind: Deployment
# 元数据部分包含关于对象的信息，比如名称和命名空间
metadata:
  labels:
    # 标签用于标识 Deployment
    app: xr-upms-biz
  # 是 Deployment 的名称
  name: xr-upms-biz
  # 表示这个 Deployment 所属的命名空间
  namespace: xr
# 规范部分定义了 Deployment 的规则和设置
spec:
  # 部署的最长时间
  progressDeadlineSeconds: 600
  # 副本数量
  replicas: 1
  # 选择器用于选择要控制的 Pod
  selector:
    matchLabels:
      app: xr-upms-biz
  # 部署策略，这里是 RollingUpdate 滚动更新策略
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  # Pod 的模板定义
  template:
    # Pod 的元数据，包括标签
    metadata:
      labels:
        app: xr-upms-biz
    # Pod 的规范，包括容器等
    spec:
      # 用于从私有镜像仓库拉取镜像的凭据
      # 需要提前在项目下配置访问阿里云的账号密码
      imagePullSecrets:
        - name: aliyun-docker-hub
      # 容器的列表
      # 镜像的路径，使用了变量 $REGISTRY、$DOCKERHUB_NAMESPACE 和 $BUILD_NUMBER
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/xr-upms-biz:SNAPSHOT-$BUILD_NUMBER
          # 用于检测容器是否准备好接收流量的检查
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          # 拉取镜像的策略
          imagePullPolicy: Always
          # 容器的名称
          name: app
          # 容器需要监听的端口
          ports:
            - containerPort: 8080
              protocol: TCP
          # 容器的资源限制
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          # 容器终止时的消息路径和策略
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      # Pod 的 DNS 策略
      dnsPolicy: ClusterFirst
      # 容器重启策略
      restartPolicy: Always
      # 终止的优雅期限
      terminationGracePeriodSeconds: 30
---
# 表示使用的 Kubernetes API 版本
apiVersion: v1
# Service 表示这是一个服务对象
kind: Service
# 元数据部分包含关于对象的信息，比如名称和命名空间
metadata:
  # 标签用于标识 Service
  labels:
    app: xr-upms-biz
  # Service 的名称
  name: xr-upms-biz
  # 表示这个 Service 所属的命名空间
  namespace: xr
# 规范部分定义了 Service 的规则和设置
spec:
  # 端口映射规则
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32607
  # 选择器用于选择要暴露的 Pod
  selector:
    app: xr-upms-biz
  # 会话关联性策略
  sessionAffinity: None
  # 服务类型，这里是 ClusterIP 集群内部访问
  type: ClusterIP
